include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error
    - always_use_package_imports
    - avoid_empty_else
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - collection_methods_unrelated_type
    - control_flow_in_finally
    - deprecated_member_use_from_same_package
    - empty_statements
    - hash_and_equals
    - literal_only_boolean_expressions
    - no_duplicate_case_values
    - no_logic_in_create_state
    - no_self_assignments
    - no_wildcard_variable_uses
    - test_types_in_equals
    - unnecessary_statements
    - use_build_context_synchronously
    - use_key_in_widget_constructors
    - valid_regexps

    # Style
    - always_put_required_named_parameters_first
    - annotate_overrides
    - annotate_redeclares
    - avoid_bool_literals_in_conditional_expressions
    - avoid_function_literals_in_foreach_calls
    - avoid_init_to_null
    - avoid_private_typedef_functions
    - avoid_positional_boolean_parameters
    - avoid_redundant_argument_values
    - avoid_return_types_on_setters
    - avoid_returning_null_for_void
    - avoid_returning_this
    - avoid_shadowing_type_parameters
    - avoid_unnecessary_containers
    - avoid_void_async
    - await_only_futures
    - camel_case_extensions
    - camel_case_types
    - cascade_invocations
    - cast_nullable_to_non_nullable
    - curly_braces_in_flow_control_structures
    - directives_ordering
    - do_not_use_environment
    - empty_catches
    - empty_constructor_bodies
    - exhaustive_cases
    - file_names
    - implementation_imports
    - implicit_call_tearoffs
    - leading_newlines_in_multiline_strings
    - matching_super_parameters
    - no_literal_bool_comparisons
    - null_closures
    - null_check_on_nullable_type_parameter
    - one_member_abstracts
    - prefer_adjacent_string_concatenation
    - prefer_conditional_assignment
    - prefer_const_constructors
    - prefer_contains
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_for_elements_to_map_fromIterable
    - prefer_foreach
    - prefer_generic_function_type_aliases
    - prefer_if_elements_to_conditional_expressions
    - prefer_if_null_operators
    - prefer_initializing_formals
    - prefer_inlined_adds
    - prefer_interpolation_to_compose_strings
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_is_not_operator
    - prefer_iterable_whereType
    - prefer_null_aware_method_calls
    - prefer_null_aware_operators
    - prefer_typing_uninitialized_variables
    - recursive_getters
    - require_trailing_commas
    - sized_box_for_whitespace
    - sized_box_shrink_expand
    - sort_child_properties_last
    - sort_unnamed_constructors_first
    - unawaited_futures
    - unnecessary_await_in_return
    - unnecessary_brace_in_string_interps
    - unnecessary_breaks
    - unnecessary_const
    - unnecessary_constructor_name
    - unnecessary_getters_setters
    - unnecessary_lambdas
    - unnecessary_new
    - unnecessary_null_aware_assignments
    - unnecessary_null_in_if_null_operators
    - unnecessary_nullable_for_final_variable_declarations
    - unnecessary_overrides
    - unnecessary_string_escapes
    - unnecessary_string_interpolations
    - unnecessary_this
    - unnecessary_to_list_in_spreads
    - use_colored_box
    - use_decorated_box
    - use_full_hex_values_for_flutter_colors
    - use_rethrow_when_possible

    # Docs
    - slash_for_doc_comments
 